export const types = {
  LOGIN_START: "LOGIN-START",
  LOGIN_SUCCESS: "LOGIN-SUCCESS",
  LOGIN_FAILURE: "LOGIN-FAILURE",
  REGISTER_SUCCUESS: "REGISTER_SUCCUESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAILURE: "LOAD_USER_FAILURE",
};
